version: '3.8'

services:
  docs:
    image: ${IMAGE:-docs}:${TAG:-latest}
    deploy:
      replicas: 1
      restart_policy: {condition: on-failure}
      update_config: {order: start-first}
      placement:
        constraints: [node.labels.frontend == true]
    networks:
      - pp-net

networks:
  pp-net:
    external: true
    name: pp-${MODE:-local}-net
